server:
  port: 8083
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/nota-social
  liquibase:
    change-log: classpath:db/changelog/changelog-main.xml
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  datasource:
    url: jdbc:mysql://localhost:3306/catalog_db?createIfNotExists=true
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        globally_quoted_identifiers: true

broker:
  queue:
    receipt-scan:
      name: default.product

imgur:
  upload-url: https://api.imgur.com/3/image
  client-id: 067de737e030833

logging:
  level:
    org:
      springframework:
        security: DEBUG